### ISSUE TITLE
upgrade to Julia 0.7

### ISSUE THREAD

**Issue by dkarrasch** [andreasnoack/TSVD.jl#11]
This is a progress tracker for an update to Julia 0.7. In particular, I'm interested in an operational connection to [`LinearMaps.jl`](https://github.com/Jutho/LinearMaps.jl), where there should appear a copy-pastable example (including a call to `tsvd`) soon on the README page. Besides the usual 3-args `mul!` there appears to be need for a 5-args `mul!` in `TSVD.jl`. This is provided for `LinearMap`s with rearranged arguments (compared to the 5-args `A_mul_B!`): `mul!(C::AbstractVector, A::LinearMap, B::AbstractVector, α::Number=1, β::Number=0)`, seemingly in accordance with the Julia 0.7 `mul!` interface.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/andreasnoack/TSVD.jl/commit/497ab28c0c6c75fc0c8e660efb18b706f5df3e18. I'll make a new release shortly.

**Comment by dkarrasch** [comment]
Runs like a charm with `LinearMaps.jl`! 👍
